require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DataProvidersController do

  before (:each) do
      @user = Factory.create(:user)
      sign_in @user
  end

  # This should return the minimal set of attributes required to create a valid
  # DataProvider. As you add validations to DataProvider, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "data_provider" }
  end

##TODO these need to be tested with an admin role once it's been implemented.


  describe "GET index" do
    it "assigns all data_providers as @data_providers" do
      data_provider = DataProvider.create! valid_attributes
      get :index, {}
      assigns(:data_providers).should eq([data_provider])
    end
  end

  describe "GET show" do
    it "assigns the requested data_provider as @data_provider" do
      data_provider = DataProvider.create! valid_attributes
      get :show, {:id => data_provider.to_param}
      assigns(:data_provider).should eq(data_provider)
    end
  end

  describe "GET new" do
    it "assigns a new data_provider as @data_provider" do
      get :new, {}
      assigns(:data_provider).should be_a_new(DataProvider)
    end
  end

  describe "GET edit" do
    it "assigns the requested data_provider as @data_provider" do
      data_provider = DataProvider.create! valid_attributes
      get :edit, {:id => data_provider.to_param}
      assigns(:data_provider).should eq(data_provider)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DataProvider" do
        expect {
          post :create, {:data_provider => valid_attributes}
        }.to change(DataProvider, :count).by(1)
      end

      it "assigns a newly created data_provider as @data_provider" do
        post :create, {:data_provider => valid_attributes}
        assigns(:data_provider).should be_a(DataProvider)
        assigns(:data_provider).should be_persisted
      end

      it "redirects to the created data_provider" do
        post :create, {:data_provider => valid_attributes}
        response.should redirect_to(root_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved data_provider as @data_provider" do
        # Trigger the behavior that occurs when invalid params are submitted
        DataProvider.any_instance.stub(:save).and_return(false)
        post :create, {:data_provider => { "name" => "invalid value" }}
        assigns(:data_provider).should be_a_new(DataProvider)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DataProvider.any_instance.stub(:save).and_return(false)
        post :create, {:data_provider => { "name" => "invalid value" }}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested data_provider" do
        data_provider = DataProvider.create! valid_attributes
        # Assuming there are no other data_providers in the database, this
        # specifies that the DataProvider created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DataProvider.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => data_provider.to_param, :data_provider => { "name" => "MyString" }}
      end

      it "assigns the requested data_provider as @data_provider" do
        data_provider = DataProvider.create! valid_attributes
        put :update, {:id => data_provider.to_param, :data_provider => valid_attributes}
        assigns(:data_provider).should eq(data_provider)
      end

      it "redirects to the data_provider" do
        data_provider = DataProvider.create! valid_attributes
        put :update, {:id => data_provider.to_param, :data_provider => valid_attributes}
        response.should redirect_to(data_provider)
      end
    end

    describe "with invalid params" do
      it "assigns the data_provider as @data_provider" do
        data_provider = DataProvider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DataProvider.any_instance.stub(:save).and_return(false)
        put :update, {:id => data_provider.to_param, :data_provider => { "name" => "invalid value" }}
        assigns(:data_provider).should eq(data_provider)
      end

      it "re-renders the 'edit' template" do
        data_provider = DataProvider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DataProvider.any_instance.stub(:save).and_return(false)
        put :update, {:id => data_provider.to_param, :data_provider => { "name" => "invalid value" }}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested data_provider" do
      data_provider = DataProvider.create! valid_attributes
      expect {
        delete :destroy, {:id => data_provider.to_param}
      }.to change(DataProvider, :count).by(-1)
    end

    it "redirects to the data_providers list" do
      data_provider = DataProvider.create! valid_attributes
      delete :destroy, {:id => data_provider.to_param}
      response.should redirect_to(data_providers_url)
    end
  end

end
