require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DownloadedDataController do

  # This should return the minimal set of attributes required to create a valid
  # DownloadedDatum. As you add validations to DownloadedDatum, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DownloadedDataController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all downloaded_data as @downloaded_data" do
      downloaded_datum = DownloadedDatum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:downloaded_data).should eq([downloaded_datum])
    end
  end

  describe "GET show" do
    it "assigns the requested downloaded_datum as @downloaded_datum" do
      downloaded_datum = DownloadedDatum.create! valid_attributes
      get :show, {:id => downloaded_datum.to_param}, valid_session
      assigns(:downloaded_datum).should eq(downloaded_datum)
    end
  end

  describe "GET new" do
    it "assigns a new downloaded_datum as @downloaded_datum" do
      get :new, {}, valid_session
      assigns(:downloaded_datum).should be_a_new(DownloadedDatum)
    end
  end

  describe "GET edit" do
    it "assigns the requested downloaded_datum as @downloaded_datum" do
      downloaded_datum = DownloadedDatum.create! valid_attributes
      get :edit, {:id => downloaded_datum.to_param}, valid_session
      assigns(:downloaded_datum).should eq(downloaded_datum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DownloadedDatum" do
        expect {
          post :create, {:downloaded_datum => valid_attributes}, valid_session
        }.to change(DownloadedDatum, :count).by(1)
      end

      it "assigns a newly created downloaded_datum as @downloaded_datum" do
        post :create, {:downloaded_datum => valid_attributes}, valid_session
        assigns(:downloaded_datum).should be_a(DownloadedDatum)
        assigns(:downloaded_datum).should be_persisted
      end

      it "redirects to the created downloaded_datum" do
        post :create, {:downloaded_datum => valid_attributes}, valid_session
        response.should redirect_to(DownloadedDatum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved downloaded_datum as @downloaded_datum" do
        # Trigger the behavior that occurs when invalid params are submitted
        DownloadedDatum.any_instance.stub(:save).and_return(false)
        post :create, {:downloaded_datum => { "name" => "invalid value" }}, valid_session
        assigns(:downloaded_datum).should be_a_new(DownloadedDatum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DownloadedDatum.any_instance.stub(:save).and_return(false)
        post :create, {:downloaded_datum => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested downloaded_datum" do
        downloaded_datum = DownloadedDatum.create! valid_attributes
        # Assuming there are no other downloaded_data in the database, this
        # specifies that the DownloadedDatum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DownloadedDatum.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => downloaded_datum.to_param, :downloaded_datum => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested downloaded_datum as @downloaded_datum" do
        downloaded_datum = DownloadedDatum.create! valid_attributes
        put :update, {:id => downloaded_datum.to_param, :downloaded_datum => valid_attributes}, valid_session
        assigns(:downloaded_datum).should eq(downloaded_datum)
      end

      it "redirects to the downloaded_datum" do
        downloaded_datum = DownloadedDatum.create! valid_attributes
        put :update, {:id => downloaded_datum.to_param, :downloaded_datum => valid_attributes}, valid_session
        response.should redirect_to(downloaded_datum)
      end
    end

    describe "with invalid params" do
      it "assigns the downloaded_datum as @downloaded_datum" do
        downloaded_datum = DownloadedDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DownloadedDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => downloaded_datum.to_param, :downloaded_datum => { "name" => "invalid value" }}, valid_session
        assigns(:downloaded_datum).should eq(downloaded_datum)
      end

      it "re-renders the 'edit' template" do
        downloaded_datum = DownloadedDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DownloadedDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => downloaded_datum.to_param, :downloaded_datum => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested downloaded_datum" do
      downloaded_datum = DownloadedDatum.create! valid_attributes
      expect {
        delete :destroy, {:id => downloaded_datum.to_param}, valid_session
      }.to change(DownloadedDatum, :count).by(-1)
    end

    it "redirects to the downloaded_data list" do
      downloaded_datum = DownloadedDatum.create! valid_attributes
      delete :destroy, {:id => downloaded_datum.to_param}, valid_session
      response.should redirect_to(downloaded_data_url)
    end
  end

end
